"""Build the detection corpus from evidence, and record what the matcher decides about it.

    uv run python -m tests.corpus.refresh          # rewrite, and report what moved
    uv run python -m tests.corpus.refresh --check  # fail if it would rewrite anything

Two files, and the split is the whole point:

- **`tools.json` is derived.** One record per tool, projected mechanically out of
  `eval/results/mcp_coverage.json` — the committed evidence a real `just field` run produces by
  launching the servers people actually install — plus the hand-authored built-ins in
  `builtins.py`, which no `tools/list` anywhere can report.
- **`decisions.json` is the answer.** What `insight.discover` gates, declines, and why, for every
  record above.

Keeping them apart means a schema change and a judgement change are different diffs. A refresh after
`just field` touches only the first; a change to the matcher touches only the second, and every line
of it is a sentence somebody can disagree with in review. That is the property being bought here:
`0 of 160` was true for the entire life of the project and nothing in the suite said so, because
nothing in the suite ever looked at a real tool.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from neti.insight.discover import classify
from tests.corpus.builtins import BUILTINS

HERE = Path(__file__).resolve().parent
SURVEY = HERE.parents[1] / "eval" / "results" / "mcp_coverage.json"
TOOLS = HERE / "tools.json"
DECISIONS = HERE / "decisions.json"

__all__ = ["DECISIONS", "TOOLS", "load_tools", "render_decisions", "render_tools"]


def _records_from_survey() -> list[dict[str, Any]]:
    survey = json.loads(SURVEY.read_text(encoding="utf-8"))
    out = []
    for server in survey["servers"]:
        if not server.get("launched"):
            continue
        for tool in server["tools"]:
            out.append(
                {
                    "id": f"mcp:{server['name']}:{tool['name']}",
                    "source": "mcp",
                    "origin": server["name"],
                    "name": tool["name"],
                    "description": tool.get("description", ""),
                    "schema": tool.get("schema") or {},
                }
            )
    return out


def _records_from_builtins() -> list[dict[str, Any]]:
    return [
        {
            "id": f"claude-code:builtin:{tool['name']}",
            "source": "claude-code",
            "origin": "builtin",
            "name": tool["name"],
            "description": tool.get("description", ""),
            "schema": tool["schema"],
        }
        for tool in BUILTINS
    ]


def render_tools() -> str:
    records = sorted(_records_from_survey() + _records_from_builtins(), key=lambda r: r["id"])
    payload = {
        "version": 1,
        "note": "Derived. Run `python -m tests.corpus.refresh` after `just field`.",
        "sources": {
            "mcp": "eval/results/mcp_coverage.json — real servers, launched and asked tools/list",
            "claude-code": "tests/corpus/builtins.py — authored; no tools/list reports these",
        },
        "tools": records,
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def _decide(record: dict[str, Any]) -> dict[str, Any]:
    spec = classify({"name": record["name"], "inputSchema": record["schema"]})
    return {
        "gated": [
            {"pointer": g.pointer, "resolver": g.resolver, "unit": g.unit} for g in spec.gated
        ],
        "declined": [
            {"param": d.param, "would_be": d.would_be, "why": d.why} for d in spec.declined
        ],
        "destructive": spec.destructive,
    }


def render_decisions(tools: list[dict[str, Any]] | None = None) -> str:
    records = tools if tools is not None else json.loads(render_tools())["tools"]
    payload = {
        "version": 1,
        "note": (
            "What `insight.discover` decides about every tool in tools.json. Regenerated by "
            "`python -m tests.corpus.refresh`; every line is a judgement, so read the diff."
        ),
        "decisions": {r["id"]: _decide(r) for r in records},
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def load_tools() -> list[dict[str, Any]]:
    return list(json.loads(TOOLS.read_text(encoding="utf-8"))["tools"])


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail instead of writing")
    args = parser.parse_args(argv)

    wanted = {TOOLS: render_tools()}
    wanted[DECISIONS] = render_decisions(json.loads(wanted[TOOLS])["tools"])

    stale = [
        path
        for path, text in wanted.items()
        if not path.exists() or path.read_text(encoding="utf-8") != text
    ]
    if args.check:
        for path in stale:
            print(f"stale: {path.relative_to(HERE.parents[1])}")
        return 1 if stale else 0

    for path, text in wanted.items():
        path.write_text(text, encoding="utf-8")
    decisions = json.loads(wanted[DECISIONS])["decisions"]
    gated = sum(1 for d in decisions.values() if d["gated"])
    print(f"wrote {len(decisions)} tools, {gated} gated")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
