"""The decision record: what an auditor reads, and what `neti verify` replays.

Design constraints that shaped this:

- The record must be reproducible from stored inputs. So it stores the `Resolution` objects, not
  just the numbers, and a `policy_digest` — the verdict is a function of `(resolutions, policy)`,
  so both halves have to be in the file.
- The number's provenance is `provider_snapshot` + `resolved_at`, not a claim that the directory
  would answer the same way tomorrow. `neti` sells an auditable bound, not freshness.
- Nothing that enters `chained` may be a float, and no timestamp generated by *this* process may
  either — `decided_at` is supplied by the caller so the core stays clock-free and the record stays
  replayable.
"""

from __future__ import annotations

from hashlib import blake2b
from typing import Any

from pydantic import Field

from neti.core.canonical import canonical_bytes
from neti.core.redact import redact_args
from neti.core.types import Decision, Frozen

__all__ = ["SCHEMA", "SCHEMA_V1", "DecisionRecord", "chain_digest", "verify_chain"]

SCHEMA = "neti.decision.v2"
SCHEMA_V1 = "neti.decision.v1"
"""The previous schema, still readable and still verifiable.

v2 adds one field — `synthetic` — and the *only* reason this is a version rather than an additive
field is that `chained` below is what `verify_chain` recomputes. Adding a key to it unconditionally
would change the recomputed digest of every record ever written, so a chain produced last week would
report as tampered with. A record's digest has to keep meaning what it meant on the day it was
sealed, or the audit artefact is worth nothing.
"""

_DIGEST_BYTES = 32


def chain_digest(prev: str | None, chained: dict[str, Any]) -> str:
    """`blake2b(prev_digest || canonical_json(chained))`, hex, 256-bit.

    blake2b rather than blake3: it is in the standard library, and hashing a few hundred bytes per
    decision is not a place where blake3's throughput advantage is worth a dependency.
    """
    h = blake2b(digest_size=_DIGEST_BYTES)
    h.update((prev or "").encode("ascii"))
    h.update(canonical_bytes(chained))
    return h.hexdigest()


class DecisionRecord(Frozen):
    schema_: str = Field(default=SCHEMA, alias="schema")
    decision_id: str
    session_id: str | None = None
    decided_at: str
    """ISO-8601, supplied by the caller. The core never reads a clock."""

    tool: str
    args: dict[str, Any] = Field(default_factory=dict)
    redacted: tuple[str, ...] = ()
    """Pointers whose values were credential-shaped and were replaced before writing.

    Named rather than silently dropped. A log that quietly removed a field would leave a reader
    unable to tell "the agent sent no key" from "the agent sent a key and we hid it", and those are
    very different facts about what happened."""

    verdict: str
    rule: str
    mode: str
    causes: tuple[dict[str, Any], ...] = ()
    budget: dict[str, Any] | None = None
    provenance: dict[str, Any] | None = None
    """What put this session downstream of untrusted input, when something did.

    Outside `chained` on purpose, and the reason is the same one that made `synthetic` a schema
    version: adding a key to the digest payload unconditionally would change the recomputed digest
    of every record ever written, so a chain sealed last week would report as tampered with. This is
    annotation — the *verdict* it produced is already covered, because the tightened ceiling appears
    in `causes[].ceiling` like any other. A tamperer stripping this makes the record less legible,
    not more permissive."""
    policy_digest: str
    code_version: str

    synthetic: bool = False
    """True when the magnitudes in this record came from the synthetic tenant, not a provider.

    `--demo` exists so somebody can see the whole path work with no credentials, and it produces
    numbers that are exact, confident and entirely invented: 41,203 principals, `direction: exact`,
    sealed into the same hash chain by the same code. Nothing distinguished such a record from a
    real one. Point a demo run at the ordinary records file — which is the default — and fabricated
    traffic interleaves with measured traffic, `neti report` averages the two, `neti propose`
    derives ceilings partly from fiction, and an auditor reading the chain cannot tell.

    Inside the digest, so it cannot be stripped: a tamperer who removed the marker to pass synthetic
    evidence off as measured would break the chain, which is the same reason `redacted` is in there.
    """

    prev_digest: str | None = None
    record_digest: str = ""

    @property
    def chained(self) -> dict[str, Any]:
        """Exactly the fields the digest covers. Anything outside this is annotation, not evidence.

        `args` is deliberately included: the verdict is meaningless without the call it judged, and
        audit formats that drop arguments cannot carry evidence at all. What they hold has already
        been through `core/redact.py`, which replaces credential-shaped values while leaving every
        gated target — the evidence itself — untouched.

        `redacted` is in here too, and that placement is the point: a tamperer who stripped the
        marker to make a hidden field look like an absent one would break the digest.
        """
        base: dict[str, Any] = {
            "schema": self.schema_,
            "decision_id": self.decision_id,
            "session_id": self.session_id,
            "decided_at": self.decided_at,
            "tool": self.tool,
            "args": self.args,
            "redacted": list(self.redacted),
            "verdict": self.verdict,
            "rule": self.rule,
            "mode": self.mode,
            "causes": list(self.causes),
            "budget": self.budget,
            "policy_digest": self.policy_digest,
            "code_version": self.code_version,
        }
        if self.schema_ != SCHEMA_V1:
            # Version-conditional, and this is the whole compatibility story. A v1 record recomputes
            # exactly the fields it was sealed over, so files written before v2 keep verifying; a v2
            # record covers the marker too, so it cannot be stripped.
            base["synthetic"] = self.synthetic
        return base

    def sealed(self, prev_digest: str | None) -> DecisionRecord:
        """Return a copy with the chain links filled in."""
        staged = self.model_copy(update={"prev_digest": prev_digest, "record_digest": ""})
        return staged.model_copy(
            update={"record_digest": chain_digest(prev_digest, staged.chained)}
        )


def build_record(
    decision: Decision,
    *,
    decision_id: str,
    decided_at: str,
    policy_digest: str,
    code_version: str,
    args: dict[str, Any] | None = None,
    session_id: str | None = None,
    provenance: dict[str, Any] | None = None,
    prev_digest: str | None = None,
    synthetic: bool = False,
) -> DecisionRecord:
    """Assemble a sealed record from a decision.

    One cause per gated argument, each naming the pointer, the unit, the resolved magnitude, the
    direction, the band that tripped and the resolution's provenance. That is the whole explanation
    of a verdict, and it is why a third party can check the answer without trusting us.
    """
    causes = tuple(
        {
            "pointer": a.pointer,
            "target": a.target,
            "verdict": a.verdict.name.lower(),
            "rule": a.rule,
            "unit": a.resolution.unit.value,
            "state": a.resolution.state.name.lower(),
            "magnitude": a.resolution.magnitude,
            "direction": a.resolution.direction.value,
            "breakdown": dict(sorted(a.resolution.breakdown.items())),
            "over_block_possible": a.over_block_possible,
            "ceiling": None if a.tripped is None else a.tripped.above,
            "breaches": [
                {
                    "source": b.source,
                    "observed": b.observed,
                    "above": b.above,
                    "verdict": b.verdict.name.lower(),
                }
                for b in a.breaches
            ],
            # Why there is no number, and whether that absence is dangerous. Two scalars rather
            # than the whole `evidence` map: evidence is provider-shaped, arbitrarily deep and may
            # hold floats, and nothing may enter `chained` that a canonical encoder cannot pin.
            #
            # Additive within v2 and safe, for a reason worth stating: `causes` entries are stored
            # dicts, not models, so a record written last week is re-read exactly as it was written
            # and recomputes the digest it was sealed with. A new key appears only in records built
            # after this line existed. That is not true of a field on `DecisionRecord` itself, which
            # is why `synthetic` needed a schema version and this does not.
            "reason": a.resolution.evidence.get("reason"),
            "destructive": a.resolution.evidence.get("destructive"),
            "consistency": a.resolution.consistency,
            "resolved_at": (
                None if a.resolution.resolved_at is None else a.resolution.resolved_at.isoformat()
            ),
            "provider_snapshot": a.resolution.provider_snapshot,
        }
        for a in decision.args
    )
    budget = None
    if decision.budget is not None:
        budget = {
            "verdict": decision.budget.verdict.name.lower(),
            "unit": None if decision.budget.unit is None else decision.budget.unit.value,
            "running_total": decision.budget.running_total,
            "ceiling": None if decision.budget.tripped is None else decision.budget.tripped.above,
            "rule": decision.budget.rule,
        }

    # Credential-shaped arguments never reach the file. The record is the artefact this product
    # asks people to keep and hand to an auditor, so a token passed to a tool must not be written
    # into it — see `core/redact.py`. The gated pointers are exempt: those are the evidence, they
    # are already in `causes`, and redacting them would destroy what the record is for.
    gated = {a.pointer for a in decision.args}
    safe_args, redacted = redact_args(args or {}, keep=gated)

    return DecisionRecord(
        decision_id=decision_id,
        session_id=session_id,
        decided_at=decided_at,
        tool=decision.tool,
        args=safe_args,
        redacted=tuple(redacted),
        verdict=decision.verdict.name.lower(),
        rule=decision.rule,
        mode=decision.mode_applied,
        causes=causes,
        budget=budget,
        provenance=provenance,
        policy_digest=policy_digest,
        code_version=code_version,
        synthetic=synthetic,
    ).sealed(prev_digest)


def verify_chain(records: list[DecisionRecord]) -> tuple[bool, str | None]:
    """Recompute every link. Returns `(ok, first_bad_decision_id)`."""
    prev: str | None = None
    for rec in records:
        if rec.prev_digest != prev:
            return False, rec.decision_id
        if chain_digest(prev, rec.chained) != rec.record_digest:
            return False, rec.decision_id
        prev = rec.record_digest
    return True, None
