"""The decision record: what an auditor reads, and what `neti verify` replays.

Design constraints that shaped this:

- The record must be reproducible from stored inputs. So it stores the `Resolution` objects, not
  just the numbers, and a `policy_digest` — the verdict is a function of `(resolutions, policy)`,
  so both halves have to be in the file.
- The number's provenance is `provider_snapshot` + `resolved_at`, not a claim that the directory
  would answer the same way tomorrow. `neti` sells an auditable bound, not freshness.
- Nothing that enters `chained` may be a float, and no timestamp generated by *this* process may
  either — `decided_at` is supplied by the caller so the core stays clock-free and the record stays
  replayable.
"""

from __future__ import annotations

from hashlib import blake2b
from typing import Any

from pydantic import Field

from neti.core.canonical import canonical_bytes
from neti.core.types import Decision, Frozen

__all__ = ["SCHEMA", "DecisionRecord", "chain_digest", "verify_chain"]

SCHEMA = "neti.decision.v1"
_DIGEST_BYTES = 32


def chain_digest(prev: str | None, chained: dict[str, Any]) -> str:
    """`blake2b(prev_digest || canonical_json(chained))`, hex, 256-bit.

    blake2b rather than blake3: it is in the standard library, and hashing a few hundred bytes per
    decision is not a place where blake3's throughput advantage is worth a dependency.
    """
    h = blake2b(digest_size=_DIGEST_BYTES)
    h.update((prev or "").encode("ascii"))
    h.update(canonical_bytes(chained))
    return h.hexdigest()


class DecisionRecord(Frozen):
    schema_: str = Field(default=SCHEMA, alias="schema")
    decision_id: str
    session_id: str | None = None
    decided_at: str
    """ISO-8601, supplied by the caller. The core never reads a clock."""

    tool: str
    args: dict[str, Any] = Field(default_factory=dict)
    verdict: str
    rule: str
    mode: str
    causes: tuple[dict[str, Any], ...] = ()
    budget: dict[str, Any] | None = None
    policy_digest: str
    code_version: str
    prev_digest: str | None = None
    record_digest: str = ""

    @property
    def chained(self) -> dict[str, Any]:
        """Exactly the fields the digest covers. Anything outside this is annotation, not evidence.

        `args` is deliberately included: the verdict is meaningless without the call it judged, and
        redacting arguments is what makes competing audit formats unable to carry evidence at all.
        Deployments that cannot store argument values should hash them at the edge and store the
        hash here, rather than dropping the field.
        """
        return {
            "schema": self.schema_,
            "decision_id": self.decision_id,
            "session_id": self.session_id,
            "decided_at": self.decided_at,
            "tool": self.tool,
            "args": self.args,
            "verdict": self.verdict,
            "rule": self.rule,
            "mode": self.mode,
            "causes": list(self.causes),
            "budget": self.budget,
            "policy_digest": self.policy_digest,
            "code_version": self.code_version,
        }

    def sealed(self, prev_digest: str | None) -> DecisionRecord:
        """Return a copy with the chain links filled in."""
        staged = self.model_copy(update={"prev_digest": prev_digest, "record_digest": ""})
        return staged.model_copy(
            update={"record_digest": chain_digest(prev_digest, staged.chained)}
        )


def build_record(
    decision: Decision,
    *,
    decision_id: str,
    decided_at: str,
    policy_digest: str,
    code_version: str,
    args: dict[str, Any] | None = None,
    session_id: str | None = None,
    prev_digest: str | None = None,
) -> DecisionRecord:
    """Assemble a sealed record from a decision.

    One cause per gated argument, each naming the pointer, the unit, the resolved magnitude, the
    direction, the band that tripped and the resolution's provenance. That is the whole explanation
    of a verdict, and it is why a third party can check the answer without trusting us.
    """
    causes = tuple(
        {
            "pointer": a.pointer,
            "target": a.target,
            "verdict": a.verdict.name.lower(),
            "rule": a.rule,
            "unit": a.resolution.unit.value,
            "state": a.resolution.state.name.lower(),
            "magnitude": a.resolution.magnitude,
            "direction": a.resolution.direction.value,
            "breakdown": dict(sorted(a.resolution.breakdown.items())),
            "over_block_possible": a.over_block_possible,
            "ceiling": None if a.tripped is None else a.tripped.above,
            "breaches": [
                {
                    "source": b.source,
                    "observed": b.observed,
                    "above": b.above,
                    "verdict": b.verdict.name.lower(),
                }
                for b in a.breaches
            ],
            "consistency": a.resolution.consistency,
            "resolved_at": (
                None if a.resolution.resolved_at is None else a.resolution.resolved_at.isoformat()
            ),
            "provider_snapshot": a.resolution.provider_snapshot,
        }
        for a in decision.args
    )
    budget = None
    if decision.budget is not None:
        budget = {
            "verdict": decision.budget.verdict.name.lower(),
            "unit": None if decision.budget.unit is None else decision.budget.unit.value,
            "running_total": decision.budget.running_total,
            "ceiling": None if decision.budget.tripped is None else decision.budget.tripped.above,
            "rule": decision.budget.rule,
        }

    return DecisionRecord(
        decision_id=decision_id,
        session_id=session_id,
        decided_at=decided_at,
        tool=decision.tool,
        args=args or {},
        verdict=decision.verdict.name.lower(),
        rule=decision.rule,
        mode=decision.mode_applied,
        causes=causes,
        budget=budget,
        policy_digest=policy_digest,
        code_version=code_version,
    ).sealed(prev_digest)


def verify_chain(records: list[DecisionRecord]) -> tuple[bool, str | None]:
    """Recompute every link. Returns `(ok, first_bad_decision_id)`."""
    prev: str | None = None
    for rec in records:
        if rec.prev_digest != prev:
            return False, rec.decision_id
        if chain_digest(prev, rec.chained) != rec.record_digest:
            return False, rec.decision_id
        prev = rec.record_digest
    return True, None
