"""Build the landing page from `site/page.html` and the generated media.

Two outputs from one source, because they are wanted in two shapes and keeping two copies of a
landing page in sync by hand is how a landing page starts lying:

    docs/index.html    a complete document, which GitHub Pages serves from /docs
    build/page.html    the body alone, for publishing as a preview before anything is committed

`{{MEDIA:name}}` in the source is replaced by `docs/media/name.svg` as a base64 `data:` URI. Inlined
rather than linked for two reasons: the page then works from a file:// URL, an email attachment or a
preview host with no relative paths at all, and — the reason that matters — the images stay the ones
`tools/make_media.py` generates from the pinned transcripts. The landing page inherits the property
the README has: it cannot show something the product no longer prints.

    just site           # rewrite both outputs
    just site --check   # fail if either is stale

Regenerating is cheap and deterministic, so `tests/property/test_media_is_current.py` checks the
committed `docs/index.html` the same way it checks the SVGs.
"""

from __future__ import annotations

import argparse
import base64
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SOURCE = REPO / "site" / "page.html"
MEDIA = REPO / "docs" / "media"
PAGE = REPO / "docs" / "index.html"
FRAGMENT = REPO / "build" / "page.html"

PLACEHOLDER = re.compile(r"\{\{MEDIA:([a-z0-9_]+)\}\}")

TITLE = "neti — how big is this?"
DESCRIPTION = (
    "A preflight gate for agent tool calls. neti resolves what a call will actually touch before "
    "it runs, compares that count to a ceiling you declared, and stops it when it does not fit."
)


def _data_uri(name: str) -> str:
    svg = MEDIA / f"{name}.svg"
    if not svg.exists():
        raise SystemExit(
            f"{svg.relative_to(REPO)} is missing — run `just media` first, since the page is built "
            "from the same images the README uses"
        )
    encoded = base64.b64encode(svg.read_bytes()).decode("ascii")
    return f"data:image/svg+xml;base64,{encoded}"


def fragment() -> str:
    """The body: styles, markup and script, with every image inlined. No document wrapper."""
    return PLACEHOLDER.sub(lambda m: _data_uri(m.group(1)), SOURCE.read_text(encoding="utf-8"))


def document(body: str) -> str:
    """The same body inside a complete document, for a static host to serve."""
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{TITLE}</title>
<meta name="description" content="{DESCRIPTION}">
<meta property="og:title" content="{TITLE}">
<meta property="og:description" content="{DESCRIPTION}">
<meta property="og:type" content="website">
<meta name="twitter:card" content="summary_large_image">
<style>
  *, *::before, *::after {{ box-sizing: border-box; }}
  html {{ -webkit-text-size-adjust: 100%; }}
  body {{ margin: 0; }}
  img {{ max-width: 100%; }}
</style>
</head>
<body>
<!-- Generated by tools/make_site.py from site/page.html. Edit that, then run `just site`. -->
{body}
</body>
</html>
"""


def expected() -> dict[Path, str]:
    body = fragment()
    return {PAGE: document(body), FRAGMENT: body}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="do not write; exit 1 if stale")
    args = parser.parse_args()

    stale: list[str] = []
    for path, text in expected().items():
        # build/ is a scratch output and is not committed, so --check only judges docs/index.html.
        if args.check and path == FRAGMENT:
            continue
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if args.check:
            stale.append(f"{path.relative_to(REPO)} — {'missing' if current is None else 'stale'}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO)}  ({len(text) // 1024} KB)")

    if stale:
        print("\n".join(stale), file=sys.stderr)
        print("\nrun `just site` and commit the result.", file=sys.stderr)
        return 1

    if args.check:
        print("docs/index.html is current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
