"""Rewrite README.md's relative links absolute, for the copy PyPI shows.

PyPI renders the long description with no base URL, so every relative path in it is dead: five
`<img src="docs/media/...">` become broken images and every `[SCOPE.md](SCOPE.md)` becomes a broken
link. That is the first thing a stranger sees on the project page, and it is the kind of defect
nobody notices from a checkout because the paths resolve there perfectly.

Generated rather than hand-maintained. Two READMEs kept in sync by editing both is two READMEs that
drift, and the one that drifts is always the one fewer people read.

    just readme-pypi           # rewrite README.pypi.md
    just readme-pypi --check   # fail if it is stale

`tests/property/test_media_is_current.py` checks it the same way it checks the images and the
landing page, so a README edit that is not reflected here fails the build.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SOURCE = REPO / "README.md"
TARGET = REPO / "README.pypi.md"

RAW = "https://raw.githubusercontent.com/Neti-Security/neti/main"
BLOB = "https://github.com/Neti-Security/neti/blob/main"

BANNER = (
    "<!-- Generated by tools/make_readme_pypi.py from README.md. Edit that, then run "
    "`just readme-pypi`. -->\n"
)


def _absolute(text: str) -> str:
    """Every relative reference, pointed at the repository it came from."""
    # <img src="docs/media/x.svg"> and any other relative src=
    text = re.sub(r'src="(?!https?://)([^"]+)"', rf'src="{RAW}/\1"', text)
    # href="LICENSING.md" in the raw HTML blocks
    text = re.sub(r'href="(?!https?://|#)([^"]+)"', rf'href="{BLOB}/\1"', text)
    # [SCOPE.md](SCOPE.md) and [`tools/x.py`](tools/x.py) in the markdown
    text = re.sub(r"\]\((?!https?://|#)([^)]+)\)", rf"]({BLOB}/\1)", text)
    return text


def expected() -> str:
    return BANNER + _absolute(SOURCE.read_text(encoding="utf-8"))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="do not write; exit 1 if stale")
    args = parser.parse_args()

    want = expected()
    have = TARGET.read_text(encoding="utf-8") if TARGET.exists() else None
    if have == want:
        if args.check:
            print(f"{TARGET.name} is current")
        return 0

    if args.check:
        print(
            f"{TARGET.relative_to(REPO)} is {'missing' if have is None else 'stale'}.\n"
            "Run `just readme-pypi` and commit the result.",
            file=sys.stderr,
        )
        return 1

    TARGET.write_text(want, encoding="utf-8")
    remaining = len(re.findall(r'src="(?!https?://)', want)) + len(
        re.findall(r"\]\((?!https?://|#)", want)
    )
    print(f"wrote {TARGET.relative_to(REPO)} ({remaining} relative references left)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
