"""Build the landing page from `site/page.html` and the generated media.

Two outputs from one source, because they are wanted in two shapes and keeping two copies of a
landing page in sync by hand is how a landing page starts lying:

    docs/index.html    a complete document, which GitHub Pages serves from /docs
    build/page.html    the body alone, for publishing as a preview before anything is committed

`{{MEDIA:name}}` in the source is replaced by `docs/media/name.svg` as a base64 `data:` URI. Inlined
rather than linked for two reasons: the page then works from a file:// URL, an email attachment or a
preview host with no relative paths at all, and — the reason that matters — the images stay the ones
`tools/make_media.py` generates from the pinned transcripts. The landing page inherits the property
the README has: it cannot show something the product no longer prints.

    just site           # rewrite both outputs
    just site --check   # fail if either is stale

Regenerating is cheap and deterministic, so `tests/property/test_media_is_current.py` checks the
committed `docs/index.html` the same way it checks the SVGs.
"""

from __future__ import annotations

import argparse
import base64
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SOURCE = REPO / "site" / "page.html"
CLOUD_SOURCE = REPO / "site" / "cloud.html"
MEDIA = REPO / "docs" / "media"
CONSOLE = MEDIA / "console"
PAGE = REPO / "docs" / "index.html"
CLOUD_PAGE = REPO / "docs" / "cloud" / "index.html"
FRAGMENT = REPO / "build" / "page.html"

PLACEHOLDER = re.compile(r"\{\{MEDIA:([a-z0-9_]+)\}\}")

# A second kind of image, kept syntactically distinct because it carries a weaker guarantee. The
# `{{MEDIA:…}}` SVGs are generated from transcripts the suite pins byte for byte and cannot show
# something the product no longer prints. These are screenshots of a running console, taken by hand;
# nothing can tell you automatically when they stop being true. `docs/media/console/PROVENANCE.md`
# records when each was taken and the exact commands that reproduce it, because the alternative is
# leaving somebody to discover the difference.
CONSOLE_PLACEHOLDER = re.compile(r"\{\{CONSOLE:([a-z0-9_]+)\}\}")

TITLE = "neti — how big is this?"
DESCRIPTION = (
    "A preflight gate for agent tool calls. neti resolves what a call will actually touch before "
    "it runs, compares that count to a ceiling you declared, and stops it when it does not fit."
)


def _data_uri(path: Path, mime: str, hint: str) -> str:
    if not path.exists():
        raise SystemExit(f"{path.relative_to(REPO)} is missing — {hint}")
    return f"data:{mime};base64,{base64.b64encode(path.read_bytes()).decode('ascii')}"


def fragment(source: Path = SOURCE) -> str:
    """The body: styles, markup and script, with every image inlined. No document wrapper."""
    text = source.read_text(encoding="utf-8")
    text = PLACEHOLDER.sub(
        lambda m: _data_uri(
            MEDIA / f"{m.group(1)}.svg",
            "image/svg+xml",
            "run `just media` first, since the page uses the same images the README does",
        ),
        text,
    )
    return CONSOLE_PLACEHOLDER.sub(
        lambda m: _data_uri(
            CONSOLE / f"{m.group(1)}.png",
            "image/png",
            "see docs/media/console/PROVENANCE.md for how to re-take it",
        ),
        text,
    )


def document(body: str, *, title: str = "", description: str = "") -> str:
    """The same body inside a complete document, for a static host to serve."""
    title = title or TITLE
    description = description or DESCRIPTION
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{description}">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{description}">
<meta property="og:type" content="website">
<meta name="twitter:card" content="summary_large_image">
<style>
  *, *::before, *::after {{ box-sizing: border-box; }}
  html {{ -webkit-text-size-adjust: 100%; }}
  body {{ margin: 0; }}
  img {{ max-width: 100%; }}
</style>
</head>
<body>
<!-- Generated by tools/make_site.py from site/page.html. Edit that, then run `just site`. -->
{body}
</body>
</html>
"""


CLOUD_TITLE = "neti cloud — approvals, org policy and fleet audit"
CLOUD_DESCRIPTION = (
    "The paid tier: the things one machine cannot do. Coming soon. The gate itself is "
    "Apache-2.0 and complete without it."
)


def csp_hashes(html: str, tag: str) -> list[str]:
    """`sha256-…` for every inline `<tag>` block in a built page.

    The page inlines its own styles, script and images on purpose — `fragment()` says why: it has to
    work from a `file://` URL, an email attachment or a preview host with no relative paths. That
    rules out `script-src 'self'`, and it would be an ugly thing for *this* product to ship
    `'unsafe-inline'` and hope nobody reads the header.

    So the inline blocks are hashed and named in `vercel.json` instead. A stale hash fails
    `test_the_csp_covers_what_the_page_actually_inlines` rather than silently blocking the page's
    own script in a browser, which is a failure a visitor would find before anybody here did.
    """
    import hashlib
    import re

    out: list[str] = []
    for block in re.findall(rf"<{tag}[^>]*>(.*?)</{tag}>", html, re.S):
        digest = hashlib.sha256(block.encode("utf-8")).digest()
        out.append("sha256-" + base64.b64encode(digest).decode("ascii"))
    return out


def expected() -> dict[Path, str]:
    """Every page this builds, and what each should contain.

    A dict rather than two named returns because `--check` and `main` both walk it, and a page that
    somebody adds to one and forgets in the other is a page that goes stale without anything saying
    so — which is the failure this whole file exists to prevent for the images.
    """
    body = fragment()
    pages = {PAGE: document(body), FRAGMENT: body}
    if CLOUD_SOURCE.exists():
        pages[CLOUD_PAGE] = document(
            fragment(CLOUD_SOURCE), title=CLOUD_TITLE, description=CLOUD_DESCRIPTION
        )
    return pages


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="do not write; exit 1 if stale")
    args = parser.parse_args()

    stale: list[str] = []
    for path, text in expected().items():
        # build/ is a scratch output and is not committed, so --check only judges docs/index.html.
        if args.check and path == FRAGMENT:
            continue
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if args.check:
            stale.append(f"{path.relative_to(REPO)} — {'missing' if current is None else 'stale'}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO)}  ({len(text) // 1024} KB)")

    if stale:
        print("\n".join(stale), file=sys.stderr)
        print("\nrun `just site` and commit the result.", file=sys.stderr)
        return 1

    if args.check:
        print("docs/index.html is current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
